Fix: version Logging
plivo/plivo-dotnet pull request #186
Opened 2022-01-21 12:46 UTC by huzaif-plivo

2022-01-21 13:05 UTC, narayana-plivo requested changes
How this PR helping Log SDK version in the HTTP request ? Please add more detail

2022-01-21 13:18 UTC, huzaif-plivo commented
> How this PR helping Log SDK version in the HTTP request ? Please add more detail

@narayana-plivo Whenever a request is made, the logging tool display's the current SDK version & language. Since the version.json file wasn't updated, incorrect version was sent even though the SDK is on a different version. Hence I have updated version.json with the current SDK version.

2022-01-23 11:13 UTC, prashantp-plivo approved these changes

2022-01-24 03:47 UTC, narayana-plivo approved these changes

2022-01-25 05:34 UTC, merged